# Generated by Django 5.1.2 on 2024-11-01 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='No title available', max_length=255)),
                ('article_authors', models.JSONField(default=list)),
                ('publication_date', models.CharField(blank=True, default='No date available', max_length=255, null=True)),
                ('article_content', models.TextField(default='No content available')),
                ('top_image', models.URLField(blank=True, default='No image available', max_length=2048, null=True)),
                ('article_keywords', models.JSONField(default=list)),
                ('article_summary', models.TextField(blank=True, default='No summary available', null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post_manager.post')),
            ],
        ),
    ]
